---
app_cli_packages:
  - htop
  - tmux
  - jq
  - ripgrep
  - fd-find
  - bind-utils
  - lsof
  - tcpdump
  - rsync
  - tree
  - vim-enhanced
  - mosh
  - bash-completion
  - git
  - wget
  - curl
  - unzip
  - tar
  - which
  - file
  - socat  # used by ~/.ssh/config ProxyCommand for SSH-over-HTTPS-CONNECT
app_cli_mosh_open_firewall: true
app_cli_mosh_firewall_port_min: 60000
app_cli_mosh_firewall_port_max: 61000
