---
common_xrdp_packages:
  - xrdp
  - xrdp-selinux
  - xorgxrdp
common_xrdp_xfce_packages:
  - xfce4-session
  - xfdesktop
  - xfwm4
  - xfce4-panel
  - xfce4-terminal
  - Thunar
common_xrdp_service_name: xrdp
common_xrdp_firewall_port: 3389
common_xrdp_open_firewall: true
common_xrdp_xsession_command: /usr/bin/xfce4-session
common_xrdp_skel_enabled: true
common_xrdp_selinux_restorecon: true

common_xrdp_ini_entries:
  - section: Globals
    option: security_layer
    value: tls
  - section: Globals
    option: tls_min_version
    value: "1.2"
  - section: Globals
    option: tcp_nodelay
    value: "true"
  - section: Globals
    option: tcp_keepalive
    value: "true"
  - section: Globals
    option: bitmap_compression
    value: "true"
  - section: Globals
    option: bulk_compression
    value: "true"
  - section: Globals
    option: new_cursors
    value: "true"
  - section: Globals
    option: max_bpp
    value: "24"

common_xrdp_sesman_ini_entries:
  - section: Security
    option: AllowRootLogin
    value: "false"
