---
app_vscode_rpm: code-1.120.0-1778619100.el8.x86_64.rpm
app_vscode_sha256: ""
app_vscode_package_dir: "{{ common_storage_mount_point | default('/mnt/data') }}/apps/packages"
app_vscode_plugins_subdir: plugins
