---
common_sshd_dropin_path: /etc/ssh/sshd_config.d/50-devmachine.conf
common_sshd_client_alive_interval: 60
common_sshd_client_alive_count_max: 3
common_sshd_allow_agent_forwarding: "yes"
common_sshd_allow_tcp_forwarding: "yes"
common_sshd_x11_forwarding: "no"
common_sshd_max_startups: "100:30:200"
common_sshd_max_sessions: 20
common_sshd_tcp_keepalive: "yes"
common_sshd_compression: "delayed"
common_sshd_use_dns: "no"
common_sshd_service_name: sshd
