---
common_storage_setup_enabled: false
common_storage_device: /dev/sdb
common_storage_vg_name: vg_devdata
common_storage_lv_name: lv_workspaces
common_storage_lv_size: 100%FREE
common_storage_fs_type: xfs
common_storage_mount_point: /mnt/data
common_storage_mount_mode: "0755"
common_storage_mount_options: "defaults,noatime,nodiratime"
