---
podman_packages:
  - podman
  - fuse-overlayfs
  - slirp4netns
  - crun
  - shadow-utils
podman_docker_compat: false
podman_subuid_start: 100000
podman_subuid_count: 65536
podman_enable_lingering: true
podman_verify_rootless: true
vm_owner: []
